using System.Drawing;
using System.Windows.Forms;

namespace GUI
{
    partial class ucFeedback_Admin
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        private void InitializeComponent()
        {
            DataGridViewCellStyle dgvStyle = new DataGridViewCellStyle();
            pnlFilter = new Panel();
            lblTitle = new Label();
            cmbFilterStatus = new ComboBox();
            lblFilterStatus = new Label();
            pnlGrid = new Panel();
            dgvFeedback = new DataGridView();
            pnlDetail = new Panel();
            lblDetailTitle = new Label();
            lblCustomerName = new Label();
            lblFeedbackDate = new Label();
            txtFeedbackContent = new TextBox();
            lblRating = new Label();
            btnReply = new Button();
            btnMarkResolved = new Button();
            btnDeleteFeedback = new Button();
            pnlFilter.SuspendLayout();
            pnlGrid.SuspendLayout();
            pnlDetail.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvFeedback).BeginInit();
            SuspendLayout();
            pnlFilter.BackColor = Color.FromArgb(30, 30, 30);
            pnlFilter.Controls.Add(lblTitle);
            pnlFilter.Controls.Add(cmbFilterStatus);
            pnlFilter.Controls.Add(lblFilterStatus);
            pnlFilter.Location = new Point(20, 15);
            pnlFilter.Name = "pnlFilter";
            pnlFilter.Size = new Size(764, 50);
            pnlFilter.TabIndex = 0;
            lblTitle.AutoSize = true;
            lblTitle.Font = new Font("Segoe UI", 13F, FontStyle.Bold);
            lblTitle.ForeColor = Color.White;
            lblTitle.Location = new Point(15, 12);
            lblTitle.Name = "lblTitle";
            lblTitle.Size = new Size(200, 25);
            lblTitle.TabIndex = 0;
            lblTitle.Text = "Phản hồi khách hàng";
            lblFilterStatus.AutoSize = true;
            lblFilterStatus.Font = new Font("Segoe UI", 10F);
            lblFilterStatus.ForeColor = Color.Gray;
            lblFilterStatus.Location = new Point(450, 15);
            lblFilterStatus.Name = "lblFilterStatus";
            lblFilterStatus.Size = new Size(80, 19);
            lblFilterStatus.TabIndex = 1;
            lblFilterStatus.Text = "Trạng thái:";
            cmbFilterStatus.BackColor = Color.FromArgb(45, 45, 48);
            cmbFilterStatus.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbFilterStatus.FlatStyle = FlatStyle.Flat;
            cmbFilterStatus.Font = new Font("Segoe UI", 10F);
            cmbFilterStatus.ForeColor = Color.White;
            cmbFilterStatus.Location = new Point(540, 12);
            cmbFilterStatus.Name = "cmbFilterStatus";
            cmbFilterStatus.Size = new Size(200, 25);
            cmbFilterStatus.TabIndex = 2;
            cmbFilterStatus.SelectedIndexChanged += cmbFilterStatus_SelectedIndexChanged;
            pnlGrid.BackColor = Color.FromArgb(30, 30, 30);
            pnlGrid.Controls.Add(dgvFeedback);
            pnlGrid.Location = new Point(20, 75);
            pnlGrid.Name = "pnlGrid";
            pnlGrid.Size = new Size(764, 260);
            pnlGrid.TabIndex = 1;
            dgvFeedback.AllowUserToAddRows = false;
            dgvFeedback.AllowUserToDeleteRows = false;
            dgvFeedback.BackgroundColor = Color.FromArgb(45, 45, 48);
            dgvFeedback.BorderStyle = BorderStyle.None;
            dgvFeedback.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvStyle.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dgvStyle.BackColor = Color.FromArgb(45, 45, 48);
            dgvStyle.Font = new Font("Segoe UI", 9F);
            dgvStyle.ForeColor = Color.White;
            dgvStyle.SelectionBackColor = Color.Gray;
            dgvStyle.SelectionForeColor = Color.White;
            dgvFeedback.DefaultCellStyle = dgvStyle;
            dgvFeedback.Location = new Point(15, 15);
            dgvFeedback.Name = "dgvFeedback";
            dgvFeedback.ReadOnly = true;
            dgvFeedback.RowHeadersWidth = 51;
            dgvFeedback.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvFeedback.Size = new Size(734, 230);
            dgvFeedback.TabIndex = 0;
            dgvFeedback.SelectionChanged += dgvFeedback_SelectionChanged;
            pnlDetail.BackColor = Color.FromArgb(30, 30, 30);
            pnlDetail.Controls.Add(lblDetailTitle);
            pnlDetail.Controls.Add(lblCustomerName);
            pnlDetail.Controls.Add(lblFeedbackDate);
            pnlDetail.Controls.Add(txtFeedbackContent);
            pnlDetail.Controls.Add(lblRating);
            pnlDetail.Controls.Add(btnReply);
            pnlDetail.Controls.Add(btnMarkResolved);
            pnlDetail.Controls.Add(btnDeleteFeedback);
            pnlDetail.Location = new Point(20, 345);
            pnlDetail.Name = "pnlDetail";
            pnlDetail.Size = new Size(764, 170);
            pnlDetail.TabIndex = 2;
            lblDetailTitle.AutoSize = true;
            lblDetailTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblDetailTitle.ForeColor = Color.White;
            lblDetailTitle.Location = new Point(15, 12);
            lblDetailTitle.Name = "lblDetailTitle";
            lblDetailTitle.Size = new Size(120, 20);
            lblDetailTitle.TabIndex = 0;
            lblDetailTitle.Text = "Chi tiết phản hồi";
            lblCustomerName.AutoSize = true;
            lblCustomerName.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblCustomerName.ForeColor = Color.Orange;
            lblCustomerName.Location = new Point(15, 40);
            lblCustomerName.Name = "lblCustomerName";
            lblCustomerName.Size = new Size(150, 19);
            lblCustomerName.TabIndex = 1;
            lblCustomerName.Text = "Khách hàng: ---";
            lblFeedbackDate.AutoSize = true;
            lblFeedbackDate.Font = new Font("Segoe UI", 9F);
            lblFeedbackDate.ForeColor = Color.Gray;
            lblFeedbackDate.Location = new Point(300, 42);
            lblFeedbackDate.Name = "lblFeedbackDate";
            lblFeedbackDate.Size = new Size(100, 15);
            lblFeedbackDate.TabIndex = 2;
            lblFeedbackDate.Text = "Ngày: ---";
            lblRating.AutoSize = true;
            lblRating.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            lblRating.ForeColor = Color.Gold;
            lblRating.Location = new Point(500, 38);
            lblRating.Name = "lblRating";
            lblRating.Size = new Size(50, 21);
            lblRating.TabIndex = 3;
            lblRating.Text = "---";
            txtFeedbackContent.BackColor = Color.FromArgb(45, 45, 48);
            txtFeedbackContent.BorderStyle = BorderStyle.None;
            txtFeedbackContent.Font = new Font("Segoe UI", 10F);
            txtFeedbackContent.ForeColor = Color.White;
            txtFeedbackContent.Location = new Point(15, 68);
            txtFeedbackContent.Multiline = true;
            txtFeedbackContent.Name = "txtFeedbackContent";
            txtFeedbackContent.ReadOnly = true;
            txtFeedbackContent.Size = new Size(540, 85);
            txtFeedbackContent.TabIndex = 4;
            btnReply.BackColor = Color.SteelBlue;
            btnReply.Cursor = Cursors.Hand;
            btnReply.FlatAppearance.BorderSize = 0;
            btnReply.FlatStyle = FlatStyle.Flat;
            btnReply.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnReply.ForeColor = Color.White;
            btnReply.Location = new Point(580, 68);
            btnReply.Name = "btnReply";
            btnReply.Size = new Size(160, 35);
            btnReply.TabIndex = 5;
            btnReply.Text = "Trả lời";
            btnReply.UseVisualStyleBackColor = false;
            btnReply.Click += btnReply_Click;
            btnMarkResolved.BackColor = Color.MediumSeaGreen;
            btnMarkResolved.Cursor = Cursors.Hand;
            btnMarkResolved.FlatAppearance.BorderSize = 0;
            btnMarkResolved.FlatStyle = FlatStyle.Flat;
            btnMarkResolved.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnMarkResolved.ForeColor = Color.White;
            btnMarkResolved.Location = new Point(580, 108);
            btnMarkResolved.Name = "btnMarkResolved";
            btnMarkResolved.Size = new Size(160, 35);
            btnMarkResolved.TabIndex = 6;
            btnMarkResolved.Text = "Đã xử lý";
            btnMarkResolved.UseVisualStyleBackColor = false;
            btnMarkResolved.Click += btnMarkResolved_Click;
            btnDeleteFeedback.BackColor = Color.IndianRed;
            btnDeleteFeedback.Cursor = Cursors.Hand;
            btnDeleteFeedback.FlatAppearance.BorderSize = 0;
            btnDeleteFeedback.FlatStyle = FlatStyle.Flat;
            btnDeleteFeedback.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnDeleteFeedback.ForeColor = Color.White;
            btnDeleteFeedback.Location = new Point(15, 138);
            btnDeleteFeedback.Name = "btnDeleteFeedback";
            btnDeleteFeedback.Size = new Size(100, 25);
            btnDeleteFeedback.TabIndex = 7;
            btnDeleteFeedback.Text = "Xóa";
            btnDeleteFeedback.UseVisualStyleBackColor = false;
            btnDeleteFeedback.Click += btnDeleteFeedback_Click;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(45, 45, 48);
            Controls.Add(pnlDetail);
            Controls.Add(pnlGrid);
            Controls.Add(pnlFilter);
            Name = "ucFeedback_Admin";
            Size = new Size(804, 530);
            pnlFilter.ResumeLayout(false);
            pnlFilter.PerformLayout();
            pnlGrid.ResumeLayout(false);
            pnlDetail.ResumeLayout(false);
            pnlDetail.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvFeedback).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private Panel pnlFilter;
        private Label lblTitle;
        private ComboBox cmbFilterStatus;
        private Label lblFilterStatus;
        private Panel pnlGrid;
        private DataGridView dgvFeedback;
        private Panel pnlDetail;
        private Label lblDetailTitle;
        private Label lblCustomerName;
        private Label lblFeedbackDate;
        private TextBox txtFeedbackContent;
        private Label lblRating;
        private Button btnReply;
        private Button btnMarkResolved;
        private Button btnDeleteFeedback;
    }
}